development:
  adapter: postgresql
  database: recurring_select_development
  username: postgres
  password: postgres
  host: 127.0.0.1

test:
  adapter: postgresql
  database: recurring_select_test
  username: postgres
  password: postgres
  host: 127.0.0.1
